openapi: 3.0.9
info:
  title: OS Hub Target API Design
  description: This specification outlines proposed API design for OS Hub to facilitate discussions and gather feedback before development begins.
  version: v1
paths:
  /v1/countries:
    get:
      summary: Get list of countries supported by the OS Hub platform
      description: >
        Returns an array of countries with name and id, where id is the ISO 3166-1 alpha-2 code of the country.
      tags:
        - countries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/country"
                example: >
                  [
                    {
                      "id": "GB",
                      "name": "United Kingdom"
                    },
                    {
                      "id": "US",
                      "name": "United States"
                    }
                  ]
components:
  schemas:
    country:
      type: object
      properties:
        id:
          type: string
          description: The ISO 3166-1 alpha-2 code of the country
        name:
          type: string
          description: The name of the country
      required:
        - id
        - name
